name: Build Pybor Studio

on:
  push:
    branches: [ main, master ]

jobs:
  build_studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # GUI (eframe/egui) potřebuje v Ubuntu pár systémových grafických knihoven na kompilaci
      - name: Install Linux GUI dependencies
        run: sudo apt-get update && sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libasound2-dev

      - name: Build Pybor Studio
        run: cargo build --release

      - name: Check that Pybor Studio binary exists
        run: ls -la target/release/pybor
        
      - name: Success
        run: echo "✅ Pybor Studio se úspěšně zkompilovalo a obsahuje všechny architektury!"
