name: 3. Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish-assets:
    name: Package and Publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact: pybor.exe
            asset_name: Pybor-Studio-Windows.exe
          - os: ubuntu-latest
            artifact: pybor
            asset_name: Pybor-Studio-Linux
          - os: macos-latest
            artifact: pybor
            asset_name: Pybor-Studio-MacOS

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install GUI dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libasound2-dev

      - name: Build for Release
        run: cargo build --release

      - name: Rename files for release
        shell: bash
        run: |
          cp target/release/${{ matrix.artifact }} ${{ matrix.asset_name }}
          zip ${{ matrix.asset_name }}.zip ${{ matrix.asset_name }}

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
          draft: false
          prerelease: true
