name: 1. Compiler Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test_logic:
    name: Translate Instructions Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install System UI Dependencies (CRITICAL FIX)
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libasound2-dev libgtk-3-dev libglib2.0-dev
          
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Check Code
        run: cargo check --verbose
